/*
*	New C++ File starts here.
*	This file should be named NMLmsgExn.cc
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=NMLmsgExn.hh -o NMLmsgExn.cc
*
*	.gen script :
*		0:load NMLmsgExn.hh
*		1:clear
*		2:select_from_file NMLmsgExn.hh
*		3:generate C++ format>NMLmsgExn.cc
*		4:generate C++ update>NMLmsgExn.cc
*		5:generate C++ constructor>NMLmsgExn.cc
*		6:exit
*
*/

#include <rcs.hh>
#include "NMLmsgExn.hh"
/*
*	Constructor for NMLmsgEx
*	from NMLmsgExn.hh:19
*/
NMLmsgEx::NMLmsgEx(NMLTYPE type,long size)
	: NMLmsg(type,size)
{
	//FrameNo = (signed int) 0;
	MessageSeqNum = (signed int) 0;

}
